---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: debian-7.6

suites:
  - name: client
    run_list:
      - recipe[samba::client]
    attributes:

  - name: server
    run_list:
      - recipe[test]
      - recipe[samba::server]
    attributes:
